"""Adding upvotes to table

Revision ID: 71149b12a21e
Revises: 7c9c1996a5b1
Create Date: 2024-11-21 16:08:22.945097

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71149b12a21e'
down_revision = '7c9c1996a5b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post_hashtag', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('upvotes', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('upvotes')

    with op.batch_alter_table('post_hashtag', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DATETIME(), nullable=True))

    # ### end Alembic commands ###
